spring.application.name=<service-name>

server.servlet.context-path=/api/v1

server.port=<port-number>

//Database connection
spring.datasource.url=<database-uri>
spring.datasource.username=<database-username>
spring.datasource.password=<database-password>
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

//Eureka client configuration, this service will be automatically registered with application name i.e. inventory-service

eureka.client.service-url.defaultZone=<Eureka-server-uri>

// <Eureka-server-uri> example - http://localhost:8761/eureka

eureka.client.fetch-registry: true
eureka.client.register-with-eureka: true

eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewable-interval-in-seconds: 10
eureka.instance.lease-expiration-duration-in-seconds: 30